"""empty message

Revision ID: 188d59ee533c
Revises: 2bb96e41341e
Create Date: 2019-08-27 09:38:47.842554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188d59ee533c'
down_revision = '2bb96e41341e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('p_unfired', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'p_unfired')
    # ### end Alembic commands ###
