"""empty message

Revision ID: 2bb96e41341e
Revises: 41365e0ce175
Create Date: 2019-08-27 09:25:33.907277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb96e41341e'
down_revision = '41365e0ce175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_order', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_order', 'status')
    # ### end Alembic commands ###
