"""empty message

Revision ID: 41365e0ce175
Revises: 9ad3e7dfb7d2
Create Date: 2019-08-27 09:21:22.340657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41365e0ce175'
down_revision = '9ad3e7dfb7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    # ### end Alembic commands ###
