"""empty message

Revision ID: 6e1c1198ef06
Revises: dfdc4cdba36b
Create Date: 2019-08-02 11:09:30.232746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1c1198ef06'
down_revision = 'dfdc4cdba36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specification', sa.Column('residue', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specification', 'residue')
    # ### end Alembic commands ###
