"""empty message

Revision ID: 3569f7f51197
Revises: 2888c12dab0e
Create Date: 2019-09-06 15:21:51.881120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3569f7f51197'
down_revision = '2888c12dab0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
