"""empty message

Revision ID: 32d818a810ee
Revises: 56b5ed8d888f
Create Date: 2019-10-02 10:55:35.023970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d818a810ee'
down_revision = '56b5ed8d888f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
