"""empty message

Revision ID: 32db509f533b
Revises: af30170ccc8a
Create Date: 2019-11-05 11:41:04.993853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32db509f533b'
down_revision = 'af30170ccc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
