"""empty message

Revision ID: 40b2ad7687ed
Revises: d149d5ed29ac
Create Date: 2019-12-06 17:25:54.430373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b2ad7687ed'
down_revision = 'd149d5ed29ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('wf_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'wf_time')
    # ### end Alembic commands ###
