
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fd5a2308d3'
down_revision = 'fe38de3c9afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###