"""empty message

Revision ID: 520909fdb700
Revises: 
Create Date: 2019-06-27 12:00:04.453628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520909fdb700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
