"""empty message

Revision ID: 56b5ed8d888f
Revises: c6956219d95a
Create Date: 2019-10-02 10:36:26.225809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b5ed8d888f'
down_revision = 'c6956219d95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
