"""empty message

Revision ID: 58f166ab3c52
Revises: 6e1c1198ef06
Create Date: 2019-08-06 12:02:40.544659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d02e2abbc8'
down_revision = '58f166ab3c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###