"""empty message

Revision ID: 690207954cdf
Revises: e3de4f09988e
Create Date: 2019-08-27 10:44:58.681675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690207954cdf'
down_revision = 'e3de4f09988e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
