"""empty message

Revision ID: 6d73d9090647
Revises: 32d818a810ee
Create Date: 2019-10-21 17:15:03.016132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d73d9090647'
down_revision = '32d818a810ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
