"""empty message

Revision ID: a31ca65e6a65
Revises: 6d73d9090647
Create Date: 2019-10-30 17:17:13.363622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31ca65e6a65'
down_revision = '6d73d9090647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
