"""empty message

Revision ID: bf3537054802
Revises: 40b2ad7687ed
Create Date: 2019-12-09 17:39:29.768080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3537054802'
down_revision = '40b2ad7687ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('order_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'order_id')
    # ### end Alembic commands ###
