"""empty message

Revision ID: c15296d8779e
Revises: 58f166ab3c52
Create Date: 2019-08-07 09:53:57.073909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15296d8779e'
down_revision = '58f166ab3c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
