"""empty message

Revision ID: d149d5ed29ac
Revises: 1efdbbb7c3ac
Create Date: 2019-12-06 17:18:44.983413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd149d5ed29ac'
down_revision = '1efdbbb7c3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component', sa.Integer(), nullable=True),
    sa.Column('wf_count', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow')
    # ### end Alembic commands ###
