"""empty message

Revision ID: e3de4f09988e
Revises: c15296d8779e
Create Date: 2019-08-21 08:27:52.440157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3de4f09988e'
down_revision = 'c15296d8779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
