"""empty message

Revision ID: 223d0a9ed75a
Revises: bb4ce6a21cd2
Create Date: 2019-08-12 17:23:23.351145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223d0a9ed75a'
down_revision = 'bb4ce6a21cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('stock_count', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component', 'stock_count')
    # ### end Alembic commands ###
