"""empty message

Revision ID: 2e496e334ce6
Revises: 6d8eb079b20d
Create Date: 2020-01-22 09:14:53.697578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e496e334ce6'
down_revision = '6d8eb079b20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('drawing_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'drawing_path')
    # ### end Alembic commands ###
