"""empty message

Revision ID: 32d818a810ee
Revises: 56b5ed8d888f
Create Date: 2019-10-02 10:55:35.023970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d818a810ee'
down_revision = '56b5ed8d888f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'document', ['order_item'])
    op.create_foreign_key(None, 'stock', 'product', ['id_product'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='unique')
    # ### end Alembic commands ###
