"""empty message

Revision ID: 3445d5acc66e
Revises: c15296d8779e
Create Date: 2019-08-10 10:43:24.682769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3445d5acc66e'
down_revision = 'c15296d8779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('stock_count', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component', 'stock_count')
    # ### end Alembic commands ###
