"""empty message

Revision ID: 381fbb88e312
Revises: aedeba5b2d35
Create Date: 2019-10-29 18:43:29.691664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381fbb88e312'
down_revision = 'aedeba5b2d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_order', sa.Column('pshop_id', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_order', 'pshop_id')
    # ### end Alembic commands ###
