"""empty message

Revision ID: 3b432c35f0ac
Revises: fcde8bf5e5c0
Create Date: 2019-12-15 10:01:32.971473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b432c35f0ac'
down_revision = 'fcde8bf5e5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('comp', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('a_count', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allowed')
    # ### end Alembic commands ###
