"""empty message

Revision ID: 5714d92118fc
Revises: 6e1c1198ef06
Create Date: 2019-08-06 11:14:00.778632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5714d92118fc'
down_revision = '6e1c1198ef06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('residue', sa.Float(), nullable=True))
    op.drop_column('specification', 'residue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specification', sa.Column('residue', sa.FLOAT(), nullable=True))
    op.drop_column('component', 'residue')
    # ### end Alembic commands ###
