"""empty message

Revision ID: 58f166ab3c52
Revises: 6e1c1198ef06
Create Date: 2019-08-06 12:02:40.544659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f166ab3c52'
down_revision = '6e1c1198ef06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('unfired', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component', 'unfired')
    # ### end Alembic commands ###
