"""empty message

Revision ID: 62d02e2abbc8
Revises: a31ca65e6a65
Create Date: 2019-11-05 14:38:00.572809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d02e2abbc8'
down_revision = 'a31ca65e6a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=True),
    sa.Column('prod_shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prod_shop_id'], ['shop.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_shop')
    # ### end Alembic commands ###
