"""empty message

Revision ID: 6669d380ae0f
Revises: fe38de3c9afd
Create Date: 2019-09-04 16:02:13.348517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6669d380ae0f'
down_revision = 'fe38de3c9afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('order_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'order_status')
    # ### end Alembic commands ###
