"""empty message

Revision ID: 6d8eb079b20d
Revises: 3b432c35f0ac
Create Date: 2020-01-14 16:58:48.533115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8eb079b20d'
down_revision = '3b432c35f0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('drawing', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component', 'drawing')
    # ### end Alembic commands ###
