"""empty message

Revision ID: 91791757bd34
Revises: 381fbb88e312
Create Date: 2019-10-29 19:01:28.129994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91791757bd34'
down_revision = '381fbb88e312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
