"""empty message

Revision ID: 9ad3e7dfb7d2
Revises: 7e0a40bbb619
Create Date: 2019-08-20 12:02:36.339403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad3e7dfb7d2'
down_revision = '7e0a40bbb619'
branch_labels = None
depends_on = None
def upgrade():
    pass
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'id_product')
    # ### end Alembic commands ###
