"""empty message

Revision ID: aedeba5b2d35
Revises: 32d818a810ee
Create Date: 2019-10-18 11:32:11.573002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedeba5b2d35'
down_revision = '32d818a810ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('workflow_count', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'workflow_count')
    # ### end Alembic commands ###
