"""empty message

Revision ID: b4f3da991d6f
Revises: 030c65d45d2b
Create Date: 2019-07-10 11:18:07.366461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f3da991d6f'
down_revision = '030c65d45d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modalcomponent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parrent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['component.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parrent_id'], ['component.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modalcomponent')
    # ### end Alembic commands ###
