"""empty message

Revision ID: c73a21c0f7de
Revises: 3569f7f51197
Create Date: 2019-09-13 15:44:13.998012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73a21c0f7de'
down_revision = '3569f7f51197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
