"""empty message

Revision ID: fe38de3c9afd
Revises: 3dbd98105054
Create Date: 2019-08-27 12:48:56.972982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe38de3c9afd'
down_revision = '3dbd98105054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('n_count', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'n_count')
    # ### end Alembic commands ###
