"""empty message

Revision ID: 2888c12dab0e
Revises: 6669d380ae0f
Create Date: 2019-09-06 15:19:01.484423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2888c12dab0e'
down_revision = '6669d380ae0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
