"""empty message

Revision ID: 3dbd98105054
Revises: 690207954cdf
Create Date: 2019-08-27 10:57:48.335844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbd98105054'
down_revision = '690207954cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('na_component', sa.Integer(), nullable=True),
    sa.Column('na_product', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('arrival_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['na_component'], ['component.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['na_product'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['product_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_table('note')
    # ### end Alembic commands ###
