"""empty message

Revision ID: 56b5ed8d888f
Revises: c6956219d95a
Create Date: 2019-10-02 10:36:26.225809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b5ed8d888f'
down_revision = 'c6956219d95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('doc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('component_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('com_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['com_id'], ['component.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_shop')
    op.drop_table('shop')
    op.drop_table('obs')
    # ### end Alembic commands ###
