"""empty message

Revision ID: 78eb2bd69f3a
Revises: fcde8bf5e5c0
Create Date: 2019-12-12 17:35:27.314166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78eb2bd69f3a'
down_revision = 'fcde8bf5e5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
