"""empty message

Revision ID: b1714afce233
Revises: 78eb2bd69f3a
Create Date: 2019-12-13 09:48:40.467217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1714afce233'
down_revision = '78eb2bd69f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowed', sa.Column('comp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allowed', 'comp')
    # ### end Alembic commands ###
